### PR TITLE
Fix to work on ios with Flutter 2.10.5 and Xcode 13.

### PR DESCRIPTION
**Pull request by RobotKSR**
Hello! The plugin was not able to launch on ios cause of some null-aware operators. A little fix to work on IOS.

### CODE REVIEW

**Comment by drdDavi** [comment]
Please merge as soon as possible

**Comment by RobotKSR** [comment]
> Please merge as soon as possible

@drdDavi you can just use my fork in your pubspec.yaml while it is not merged by author.

**Comment by 3lVv0w** [comment]
could anyone merge this coz i have an issues when i try to complied

**Comment by JackJonson** [comment]
Fix errors in flutter 2.10.x, [2.1.2+1](https://pub.dev/packages/flutter_styled_toast/versions/2.1.2+1)

**Pull request closed without merging**
